/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_MILLER: () => VIEW_TYPE_MILLER,
  default: () => MillerColumnsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_MILLER = "miller-columns-view";
var ICON_ID = "miller-columns";
var ICON_SVG = '<rect x="10" y="18" width="80" height="64" rx="8" fill="none" stroke="currentColor" stroke-width="8"/><line x1="37" y1="18" x2="37" y2="82" stroke="currentColor" stroke-width="8"/><line x1="63" y1="18" x2="63" y2="82" stroke="currentColor" stroke-width="8"/>';
var REFRESH_ALL = "*";
var SUBPAGE_BLOCK_START = "<!-- miller-columns-subpages:start -->";
var SUBPAGE_BLOCK_END = "<!-- miller-columns-subpages:end -->";
var MIN_COLUMN_WIDTH = 64;
var COMPACT_COLUMN_WIDTH = 96;
var MAX_COLUMN_WIDTH = 520;
var DEFAULT_SETTINGS = {
  columnWidth: 220,
  columnWidths: [],
  appearances: {}
};
var DEFAULT_PAGE_ICON = "file-text";
var ICON_PRESETS = ["file-text", "book-open", "notebook", "library", "folder", "star", "bookmark", "lightbulb", "pen-line"];
var COLOR_PRESETS = ["", "#e06c75", "#d19a66", "#e5c07b", "#98c379", "#56b6c2", "#61afef", "#c678dd"];
function compareNames(a, b) {
  return a.name.localeCompare(b.name, void 0, {
    sensitivity: "base",
    numeric: true
  });
}
function parentPathOf(path) {
  const idx = path.lastIndexOf("/");
  return idx <= 0 ? "/" : path.substring(0, idx);
}
function errorMessage(e) {
  return e instanceof Error ? e.message : String(e);
}
function markdownLinkPath(file) {
  return file.path.replace(/\.md$/i, "");
}
function markdownPageLink(file) {
  return `[[${markdownLinkPath(file)}|${file.basename}]]`;
}
var MillerColumnsView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    /** selection[i] is the selected item in column i; only the last entry may be a file. */
    this.selection = [];
    this.activeColumn = 0;
    this.columns = [];
    this.pageLeaf = null;
    this.millerPaneWidth = null;
    this.affected = /* @__PURE__ */ new Set();
    this.refreshQueued = false;
    this.navigation = false;
  }
  getViewType() {
    return VIEW_TYPE_MILLER;
  }
  getDisplayText() {
    return "Miller Columns";
  }
  getIcon() {
    return ICON_ID;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("miller-columns");
    this.applySettings();
    this.columnsEl = contentEl.createDiv({ cls: "mc-columns" });
    this.columnsEl.setAttr("tabindex", "0");
    this.columnsEl.addEventListener("keydown", (e) => this.onKeyDown(e));
    this.registerEvent(
      this.app.vault.on("create", (f) => this.queueRefresh(this.parentsOf(f.path)))
    );
    this.registerEvent(
      this.app.vault.on("delete", (f) => this.queueRefresh(this.parentsOf(f.path)))
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        void this.plugin.moveAppearance(oldPath, file.path);
        this.queueRefresh([REFRESH_ALL]);
      })
    );
    this.registerEvent(
      this.app.workspace.on("resize", () => this.rememberMillerPaneWidth())
    );
    this.buildColumnsFrom(0);
  }
  async onClose() {
    this.columns = [];
    this.contentEl.empty();
  }
  applySettings() {
    this.contentEl.style.setProperty(
      "--mc-column-width",
      `${this.plugin.settings.columnWidth}px`
    );
    this.columns.forEach((col, i) => this.applyColumnWidth(col.el, i));
  }
  // ---------------------------------------------------------------- columns
  /** Number of columns implied by the current selection (root + one per selected folder). */
  columnCount() {
    let n = 1;
    for (const item of this.selection) {
      if (item instanceof import_obsidian.TFolder) n++;
      else break;
    }
    return n;
  }
  folderForColumn(i) {
    if (i === 0) return this.app.vault.getRoot();
    const sel = this.selection[i - 1];
    return sel instanceof import_obsidian.TFolder ? sel : null;
  }
  folderPagePath(folder) {
    if (folder.isRoot()) return null;
    return (0, import_obsidian.normalizePath)(`${folder.path}/${folder.name}.md`);
  }
  isFolderPage(folder, item) {
    const pagePath = this.folderPagePath(folder);
    return pagePath !== null && item instanceof import_obsidian.TFile && item.path === pagePath;
  }
  visibleChildren(folder) {
    const configDir = this.app.vault.configDir;
    return folder.children.filter((c) => c.path !== configDir && !this.isFolderPage(folder, c));
  }
  itemsForColumn(i) {
    const col = this.columns[i];
    if (!col) return [];
    const children = this.visibleChildren(col.folder);
    const folders = children.filter((c) => c instanceof import_obsidian.TFolder).sort(compareNames);
    const files = children.filter((c) => c instanceof import_obsidian.TFile).sort(compareNames);
    return [...folders, ...files];
  }
  /** Remove columns from `index` on, then (re)create every column the selection implies. */
  buildColumnsFrom(index, scroll = true) {
    for (const col of this.columns.splice(index)) col.el.detach();
    const total = this.columnCount();
    for (let i = this.columns.length; i < total; i++) {
      const folder = this.folderForColumn(i);
      if (!folder) break;
      const el = this.columnsEl.createDiv({ cls: "mc-column" });
      this.columns.push({ folder, el });
      this.applyColumnWidth(el, i);
      this.attachColumnHandlers(el, i);
      this.renderColumn(i);
    }
    this.updateSelectionClasses();
    if (scroll) this.scrollToNewestColumn();
  }
  renderColumn(i) {
    const col = this.columns[i];
    if (!col) return;
    col.el.empty();
    const items = this.itemsForColumn(i);
    if (items.length === 0) {
      col.el.createDiv({ cls: "mc-empty", text: "No pages. Right-click to create one." });
      this.renderResizeHandle(col.el, i);
      return;
    }
    for (const item of items) this.renderRow(col.el, i, item);
    this.renderResizeHandle(col.el, i);
  }
  applyColumnWidth(el, index) {
    const width = this.plugin.columnWidthFor(index);
    el.style.setProperty("--mc-column-width", `${width}px`);
    el.toggleClass("is-narrow", width < COMPACT_COLUMN_WIDTH);
  }
  renderResizeHandle(colEl, colIndex) {
    const handle = colEl.createDiv({ cls: "mc-resize-handle" });
    handle.setAttr("aria-label", "Resize column");
    handle.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const startX = e.clientX;
      const startWidth = this.plugin.columnWidthFor(colIndex);
      handle.addClass("is-resizing");
      const onMove = (moveEvent) => {
        const width = this.plugin.setColumnWidth(
          colIndex,
          startWidth + moveEvent.clientX - startX
        );
        this.applyColumnWidth(colEl, colIndex);
        colEl.style.setProperty("--mc-column-width", `${width}px`);
      };
      const onUp = () => {
        handle.removeClass("is-resizing");
        window.removeEventListener("pointermove", onMove);
        window.removeEventListener("pointerup", onUp);
        void this.plugin.saveSettings();
      };
      window.addEventListener("pointermove", onMove);
      window.addEventListener("pointerup", onUp);
    });
    handle.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
    });
    handle.addEventListener("dblclick", async (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.plugin.resetColumnWidth(colIndex);
      this.applyColumnWidth(colEl, colIndex);
      await this.plugin.saveSettings();
    });
  }
  renderRow(colEl, colIndex, item) {
    var _a;
    const row = colEl.createDiv({ cls: "mc-item" });
    row.dataset.path = item.path;
    row.setAttr("draggable", "true");
    const iconEl = row.createSpan({ cls: "mc-icon" });
    const appearance = this.plugin.appearanceFor(item.path);
    (0, import_obsidian.setIcon)(iconEl, (_a = appearance.icon) != null ? _a : DEFAULT_PAGE_ICON);
    if (appearance.color) iconEl.style.color = appearance.color;
    const displayName = item instanceof import_obsidian.TFile && item.extension === "md" ? item.basename : item.name;
    row.createSpan({ cls: "mc-name", text: displayName });
    if (item instanceof import_obsidian.TFolder) {
      row.createSpan({
        cls: "mc-count",
        text: String(this.visibleChildren(item).length)
      });
      row.createSpan({ cls: "mc-chevron", text: "\u203A" });
    }
    row.addEventListener("click", () => {
      this.columnsEl.focus({ preventScroll: true });
      this.selectItem(colIndex, item);
    });
    row.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.showItemMenu(e, item);
    });
    row.addEventListener("dragstart", (e) => {
      if (!e.dataTransfer) return;
      e.dataTransfer.setData("text/plain", item.path);
      e.dataTransfer.effectAllowed = "move";
    });
    if (item instanceof import_obsidian.TFolder) {
      this.addDropHandlers(row, () => item);
    }
  }
  attachColumnHandlers(el, index) {
    el.addEventListener("contextmenu", (e) => {
      if (e.target.closest(".mc-item")) return;
      e.preventDefault();
      const col = this.columns[index];
      if (col) this.showFolderMenu(e, col.folder);
    });
    this.addDropHandlers(el, () => {
      var _a, _b;
      return (_b = (_a = this.columns[index]) == null ? void 0 : _a.folder) != null ? _b : null;
    });
  }
  updateSelectionClasses() {
    const tipIndex = this.selection.length - 1;
    this.columns.forEach((col, i) => {
      const selPath = this.selection[i] ? this.selection[i].path : null;
      col.el.querySelectorAll(".mc-item").forEach((row) => {
        const selected = selPath !== null && row.dataset.path === selPath;
        row.classList.toggle("is-selected", selected);
        row.classList.toggle("is-active", selected && i === tipIndex);
      });
    });
  }
  scrollToNewestColumn() {
    window.requestAnimationFrame(() => {
      this.columnsEl.scrollLeft = this.columnsEl.scrollWidth;
    });
  }
  scrollRowIntoView(colIndex, path) {
    const col = this.columns[colIndex];
    if (!col) return;
    const rows = Array.from(col.el.querySelectorAll(".mc-item"));
    for (const row of rows) {
      if (row.dataset.path === path) {
        row.scrollIntoView({ block: "nearest" });
        return;
      }
    }
  }
  // -------------------------------------------------------------- selection
  selectItem(colIndex, item, openFile = true) {
    this.selection = this.selection.slice(0, colIndex);
    this.selection[colIndex] = item;
    this.activeColumn = colIndex;
    this.buildColumnsFrom(colIndex + 1);
    this.scrollRowIntoView(colIndex, item.path);
    if (openFile && item instanceof import_obsidian.TFile) {
      void this.openPageFile(item);
    } else if (openFile && item instanceof import_obsidian.TFolder) {
      void this.openFolderPage(item);
    }
  }
  /** Select the full ancestor chain of `item` and rebuild all columns around it. */
  revealPath(item) {
    const chain = [];
    let cur = item;
    while (cur && cur.parent) {
      chain.unshift(cur);
      cur = cur.parent;
    }
    this.selection = chain;
    this.activeColumn = Math.max(0, chain.length - 1);
    this.buildColumnsFrom(0);
    if (chain.length > 0) this.scrollRowIntoView(chain.length - 1, item.path);
  }
  // --------------------------------------------------------------- keyboard
  onKeyDown(e) {
    if (this.columns.length === 0) return;
    const col = Math.min(this.activeColumn, this.columns.length - 1);
    this.activeColumn = col;
    const items = this.itemsForColumn(col);
    const current = this.selection[col];
    const idx = current ? items.indexOf(current) : -1;
    switch (e.key) {
      case "ArrowDown": {
        if (items.length === 0) break;
        const next = items[Math.min(items.length - 1, idx + 1)];
        this.selectItem(col, next, false);
        break;
      }
      case "ArrowUp": {
        if (items.length === 0) break;
        const next = items[idx === -1 ? items.length - 1 : Math.max(0, idx - 1)];
        this.selectItem(col, next, false);
        break;
      }
      case "ArrowLeft": {
        if (col > 0) this.activeColumn = col - 1;
        break;
      }
      case "ArrowRight": {
        this.descendIntoSelectedFolder(col);
        break;
      }
      case "Enter": {
        const sel = this.selection[col];
        if (sel instanceof import_obsidian.TFile) {
          void this.openPageFile(sel);
        } else if (sel instanceof import_obsidian.TFolder) {
          void this.openFolderPage(sel);
        }
        break;
      }
      default:
        return;
    }
    e.preventDefault();
  }
  descendIntoSelectedFolder(col) {
    const sel = this.selection[col];
    if (!(sel instanceof import_obsidian.TFolder) || this.columns.length <= col + 1) return;
    this.activeColumn = col + 1;
    if (!this.selection[col + 1]) {
      const childItems = this.itemsForColumn(col + 1);
      if (childItems.length > 0) this.selectItem(col + 1, childItems[0], false);
    }
  }
  // ------------------------------------------------------------ live update
  parentsOf(path) {
    const parent = parentPathOf(path);
    return [parent, parentPathOf(parent)];
  }
  queueRefresh(paths) {
    for (const p of paths) this.affected.add(p);
    if (this.refreshQueued) return;
    this.refreshQueued = true;
    window.setTimeout(() => {
      this.refreshQueued = false;
      const affected = this.affected;
      this.affected = /* @__PURE__ */ new Set();
      this.refresh(affected);
    }, 0);
  }
  refresh(affected) {
    let valid = 0;
    while (valid < this.selection.length) {
      const item = this.selection[valid];
      if (this.app.vault.getAbstractFileByPath(item.path) !== item) break;
      if (item.parent !== this.folderForColumn(valid)) break;
      valid++;
    }
    if (valid < this.selection.length) this.selection.length = valid;
    this.activeColumn = Math.min(this.activeColumn, this.columnCount() - 1);
    this.buildColumnsFrom(this.columnCount(), false);
    const all = affected.has(REFRESH_ALL);
    this.columns.forEach((col, i) => {
      if (all || affected.has(col.folder.path)) {
        this.renderColumn(i);
        void this.syncFolderPage(col.folder);
      }
    });
    this.updateSelectionClasses();
  }
  // ---------------------------------------------------------- page content
  async openFolderPage(folder) {
    try {
      const page = await this.ensureFolderPage(folder);
      if (!page) return;
      await this.syncFolderPage(folder, page);
      if (folder.parent) await this.syncFolderPage(folder.parent);
      await this.openPageFile(page);
    } catch (e) {
      new import_obsidian.Notice("Could not open page: " + errorMessage(e));
    }
  }
  async openPageFile(file) {
    const hadPageLeaf = this.pageLeaf !== null && this.isLeafAttached(this.pageLeaf);
    const leaf = this.rightPageLeaf();
    if (!hadPageLeaf) this.restoreMillerPaneWidth();
    await leaf.openFile(file, { state: { mode: "preview" } });
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
    this.rememberMillerPaneWidthSoon();
  }
  rightPageLeaf() {
    if (this.pageLeaf && this.isLeafAttached(this.pageLeaf)) return this.pageLeaf;
    this.app.workspace.setActiveLeaf(this.leaf, { focus: false });
    this.pageLeaf = this.app.workspace.getLeaf("split", "vertical");
    return this.pageLeaf;
  }
  millerPaneEl() {
    var _a;
    return (_a = this.containerEl.closest(".workspace-tabs")) != null ? _a : this.containerEl.closest(".workspace-leaf");
  }
  rememberMillerPaneWidth() {
    var _a;
    if (!this.pageLeaf || !this.isLeafAttached(this.pageLeaf)) return;
    const width = (_a = this.millerPaneEl()) == null ? void 0 : _a.getBoundingClientRect().width;
    if (width && Number.isFinite(width)) this.millerPaneWidth = Math.round(width);
  }
  rememberMillerPaneWidthSoon() {
    window.requestAnimationFrame(() => this.rememberMillerPaneWidth());
  }
  restoreMillerPaneWidth() {
    const width = this.millerPaneWidth;
    if (!width) return;
    window.requestAnimationFrame(() => {
      const el = this.millerPaneEl();
      if (!el) return;
      el.style.width = `${width}px`;
      el.style.flexBasis = `${width}px`;
    });
  }
  isLeafAttached(target) {
    let found = false;
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf === target) found = true;
    });
    return found;
  }
  async ensureFolderPage(folder) {
    const path = this.folderPagePath(folder);
    if (!path) return null;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFile) return existing;
    if (existing) {
      new import_obsidian.Notice(`Could not create page because ${path} already exists.`);
      return null;
    }
    return await this.app.vault.create(path, this.subpageBlock(folder));
  }
  async syncFolderPage(folder, knownPage) {
    if (folder.isRoot()) return;
    try {
      const page = knownPage != null ? knownPage : await this.ensureFolderPage(folder);
      if (!page) return;
      const block = this.subpageBlock(folder);
      const raw = await this.app.vault.read(page);
      const current = this.stripGeneratedTitle(raw, folder);
      const next = this.replaceSubpageBlock(current, block);
      if (next !== raw) await this.app.vault.modify(page, next);
    } catch (e) {
      new import_obsidian.Notice("Could not update subpage links: " + errorMessage(e));
    }
  }
  subpageBlock(folder) {
    const links = this.subpageFiles(folder).map((file) => `- ${markdownPageLink(file)}`);
    const body = links.length > 0 ? `${links.join("\n")}
` : "";
    return `${SUBPAGE_BLOCK_START}
${body}${SUBPAGE_BLOCK_END}`;
  }
  subpageFiles(folder) {
    const files = [];
    for (const child of this.visibleChildren(folder)) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        files.push(child);
      }
      if (child instanceof import_obsidian.TFolder) {
        const pagePath = this.folderPagePath(child);
        const page = pagePath ? this.app.vault.getAbstractFileByPath(pagePath) : null;
        if (page instanceof import_obsidian.TFile) files.push(page);
      }
    }
    return files.sort(compareNames);
  }
  replaceSubpageBlock(content, block) {
    const start = content.indexOf(SUBPAGE_BLOCK_START);
    const end = content.indexOf(SUBPAGE_BLOCK_END);
    if (start >= 0 && end >= start) {
      const afterEnd = end + SUBPAGE_BLOCK_END.length;
      return content.substring(0, start) + block + content.substring(afterEnd);
    }
    const trimmed = content.trimEnd();
    return `${trimmed}${trimmed ? "\n\n" : ""}${block}`;
  }
  stripGeneratedTitle(content, folder) {
    const heading = `# ${folder.name}`;
    const trimmedStart = content.trimStart();
    if (trimmedStart !== heading && !trimmedStart.startsWith(`${heading}
`)) return content;
    const leadingWhitespaceLength = content.length - trimmedStart.length;
    const afterHeading = trimmedStart.substring(heading.length);
    if (!/^\s*\n\s*\n?<!-- miller-columns-subpages:start -->/.test(afterHeading)) {
      return content;
    }
    return content.substring(0, leadingWhitespaceLength) + afterHeading.trimStart();
  }
  // ---------------------------------------------------------- file actions
  showItemMenu(e, item) {
    var _a;
    const targetFolder = item instanceof import_obsidian.TFolder ? item : (_a = item.parent) != null ? _a : this.app.vault.getRoot();
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle("New page").setIcon("file-plus").onClick(() => this.createPage(targetFolder))
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Icon and color").setIcon("palette").onClick(() => new AppearanceModal(this.app, this.plugin, item, () => this.refreshPath(item)).open())
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.app, item).open())
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Delete").setIcon("trash").onClick(async () => {
        try {
          await this.app.fileManager.trashFile(item);
        } catch (err) {
          new import_obsidian.Notice("Could not delete: " + errorMessage(err));
        }
      })
    );
    menu.showAtMouseEvent(e);
  }
  refreshPath(item) {
    var _a;
    const parent = (_a = item.parent) != null ? _a : this.app.vault.getRoot();
    this.queueRefresh([parent.path]);
  }
  showFolderMenu(e, folder) {
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle("New page").setIcon("file-plus").onClick(() => this.createPage(folder))
    );
    menu.showAtMouseEvent(e);
  }
  uniquePath(folder, base, ext) {
    const prefix = folder.isRoot() ? "" : folder.path + "/";
    let candidate = base;
    let n = 1;
    while (this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(prefix + candidate + ext))) {
      candidate = `${base} ${n++}`;
    }
    return (0, import_obsidian.normalizePath)(prefix + candidate + ext);
  }
  async createPage(parent) {
    try {
      const path = this.uniquePath(parent, "Untitled", "");
      const folder = await this.app.vault.createFolder(path);
      const page = await this.ensureFolderPage(folder);
      if (page) await this.syncFolderPage(folder, page);
      await this.syncFolderPage(parent);
      this.revealPath(folder);
      if (page) await this.openPageFile(page);
    } catch (e) {
      new import_obsidian.Notice("Could not create page: " + errorMessage(e));
    }
  }
  // ------------------------------------------------------------ drag & drop
  addDropHandlers(el, getFolder) {
    el.addEventListener("dragover", (e) => {
      if (!e.dataTransfer || !e.dataTransfer.types.includes("text/plain")) return;
      e.preventDefault();
      e.stopPropagation();
      e.dataTransfer.dropEffect = "move";
      el.addClass("mc-drop-target");
    });
    el.addEventListener("dragleave", () => el.removeClass("mc-drop-target"));
    el.addEventListener("drop", (e) => {
      var _a;
      el.removeClass("mc-drop-target");
      const path = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!path) return;
      e.preventDefault();
      e.stopPropagation();
      const src = this.app.vault.getAbstractFileByPath(path);
      const target = getFolder();
      if (src && target) void this.moveInto(src, target);
    });
  }
  async moveInto(src, target) {
    if (src === target || src.parent === target) return;
    if (src instanceof import_obsidian.TFolder && (target === src || target.path.startsWith(src.path + "/"))) {
      new import_obsidian.Notice("Cannot move a folder into itself.");
      return;
    }
    const dest = (0, import_obsidian.normalizePath)((target.isRoot() ? "" : target.path + "/") + src.name);
    if (this.app.vault.getAbstractFileByPath(dest)) {
      new import_obsidian.Notice("An item with that name already exists there.");
      return;
    }
    try {
      await this.app.fileManager.renameFile(src, dest);
    } catch (e) {
      new import_obsidian.Notice("Could not move: " + errorMessage(e));
    }
  }
};
var RenameModal = class extends import_obsidian.Modal {
  constructor(app, item) {
    super(app);
    this.item = item;
  }
  onOpen() {
    this.titleEl.setText("Rename page");
    const input = this.contentEl.createEl("input", {
      cls: "mc-rename-input",
      type: "text",
      value: this.item.name
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void this.submit(input.value);
      }
    });
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Rename").setCta().onClick(() => void this.submit(input.value))
    );
    input.focus();
    if (this.item instanceof import_obsidian.TFile && this.item.extension) {
      input.setSelectionRange(0, Math.max(0, this.item.name.length - this.item.extension.length - 1));
    } else {
      input.select();
    }
  }
  async submit(name) {
    name = name.trim();
    if (!name || name.includes("/") || name.includes("\\")) {
      new import_obsidian.Notice("Invalid name.");
      return;
    }
    const parent = this.item.parent;
    const prefix = parent && !parent.isRoot() ? parent.path + "/" : "";
    const oldName = this.item.name;
    const destination = (0, import_obsidian.normalizePath)(prefix + name);
    try {
      await this.app.fileManager.renameFile(this.item, destination);
      if (this.item instanceof import_obsidian.TFolder) {
        await this.renameCompanionPage(destination, oldName, name);
      }
      this.close();
    } catch (e) {
      new import_obsidian.Notice("Rename failed: " + errorMessage(e));
    }
  }
  async renameCompanionPage(folderPath, oldFolderName, newFolderName) {
    const oldPagePath = (0, import_obsidian.normalizePath)(`${folderPath}/${oldFolderName}.md`);
    const newPagePath = (0, import_obsidian.normalizePath)(`${folderPath}/${newFolderName}.md`);
    if (oldPagePath === newPagePath) return;
    const oldPage = this.app.vault.getAbstractFileByPath(oldPagePath);
    if (!(oldPage instanceof import_obsidian.TFile)) return;
    if (this.app.vault.getAbstractFileByPath(newPagePath)) return;
    await this.app.fileManager.renameFile(oldPage, newPagePath);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AppearanceModal = class extends import_obsidian.Modal {
  constructor(app, plugin, item, onChange) {
    var _a, _b;
    super(app);
    this.plugin = plugin;
    this.item = item;
    this.onChange = onChange;
    this.icon = "";
    this.color = "";
    const appearance = plugin.appearanceFor(item.path);
    this.icon = (_a = appearance.icon) != null ? _a : DEFAULT_PAGE_ICON;
    this.color = (_b = appearance.color) != null ? _b : "";
  }
  onOpen() {
    this.titleEl.setText("Icon and color");
    this.contentEl.addClass("mc-appearance-modal");
    const preview = this.contentEl.createDiv({ cls: "mc-appearance-preview" });
    this.previewEl = preview.createSpan({ cls: "mc-appearance-preview-icon" });
    preview.createSpan({ text: this.item.name });
    this.renderPreview();
    new import_obsidian.Setting(this.contentEl).setName("Icon").setDesc("Use a Lucide icon name, such as notebook, book-open, star, or bookmark.").addText(
      (text) => text.setValue(this.icon).onChange((value) => {
        this.icon = value.trim();
        this.renderPreview();
      })
    );
    const iconGrid = this.contentEl.createDiv({ cls: "mc-picker-grid" });
    for (const icon of ICON_PRESETS) {
      const btn = iconGrid.createEl("button", { cls: "mc-icon-choice", attr: { type: "button" } });
      const iconEl = btn.createSpan();
      (0, import_obsidian.setIcon)(iconEl, icon);
      btn.setAttr("aria-label", icon);
      btn.addEventListener("click", () => {
        this.icon = icon;
        this.display();
      });
    }
    new import_obsidian.Setting(this.contentEl).setName("Color").setDesc("Choose a preset or enter any CSS color.").addText(
      (text) => text.setPlaceholder("default, #61afef, var(--text-accent)").setValue(this.color).onChange((value) => {
        this.color = value.trim();
        this.renderPreview();
      })
    );
    const colorGrid = this.contentEl.createDiv({ cls: "mc-picker-grid" });
    for (const color of COLOR_PRESETS) {
      const btn = colorGrid.createEl("button", { cls: "mc-color-choice", attr: { type: "button" } });
      btn.setAttr("aria-label", color || "Default color");
      if (color) btn.style.backgroundColor = color;
      btn.addEventListener("click", () => {
        this.color = color;
        this.display();
      });
    }
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Reset").onClick(async () => {
        delete this.plugin.settings.appearances[this.item.path];
        await this.plugin.saveSettings();
        this.onChange();
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(async () => {
        this.plugin.setAppearance(this.item.path, {
          icon: this.icon || DEFAULT_PAGE_ICON,
          color: this.color || void 0
        });
        await this.plugin.saveSettings();
        this.onChange();
        this.close();
      })
    );
  }
  display() {
    this.contentEl.empty();
    this.onOpen();
  }
  renderPreview() {
    if (!this.previewEl) return;
    this.previewEl.empty();
    (0, import_obsidian.setIcon)(this.previewEl, this.icon || DEFAULT_PAGE_ICON);
    this.previewEl.style.color = this.color;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MillerColumnsPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    (0, import_obsidian.addIcon)(ICON_ID, ICON_SVG);
    this.registerView(VIEW_TYPE_MILLER, (leaf) => new MillerColumnsView(leaf, this));
    this.addSettingTab(new MillerColumnsSettingTab(this.app, this));
    this.addRibbonIcon(ICON_ID, "Open Miller Columns", () => void this.activateView());
    this.addCommand({
      id: "open",
      name: "Open",
      callback: () => void this.activateView()
    });
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...loaded,
      columnWidths: Array.isArray(loaded == null ? void 0 : loaded.columnWidths) ? loaded.columnWidths : [],
      appearances: (loaded == null ? void 0 : loaded.appearances) && typeof loaded.appearances === "object" ? loaded.appearances : {}
    };
    this.settings.columnWidth = this.clampColumnWidth(this.settings.columnWidth);
    this.settings.columnWidths = this.settings.columnWidths.map(
      (width) => typeof width === "number" ? this.clampColumnWidth(width) : null
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MILLER)) {
      const view = leaf.view;
      if (view instanceof MillerColumnsView) view.applySettings();
    }
  }
  columnWidthFor(index) {
    const width = this.settings.columnWidths[index];
    return typeof width === "number" ? width : this.settings.columnWidth;
  }
  setColumnWidth(index, width) {
    const next = this.clampColumnWidth(width);
    this.settings.columnWidths[index] = next;
    return next;
  }
  resetColumnWidth(index) {
    this.settings.columnWidths[index] = null;
  }
  appearanceFor(path) {
    var _a;
    return (_a = this.settings.appearances[path]) != null ? _a : {};
  }
  setAppearance(path, appearance) {
    this.settings.appearances[path] = appearance;
  }
  async moveAppearance(oldPath, newPath) {
    let changed = false;
    const next = {};
    for (const [path, appearance] of Object.entries(this.settings.appearances)) {
      let targetPath = path;
      if (path === oldPath) {
        targetPath = newPath;
      } else if (path.startsWith(oldPath + "/")) {
        targetPath = newPath + path.substring(oldPath.length);
      }
      if (targetPath !== path) changed = true;
      next[targetPath] = appearance;
    }
    if (!changed) return;
    this.settings.appearances = next;
    await this.saveSettings();
  }
  clampColumnWidth(width) {
    if (!Number.isFinite(width)) return DEFAULT_SETTINGS.columnWidth;
    return Math.min(MAX_COLUMN_WIDTH, Math.max(MIN_COLUMN_WIDTH, Math.round(width)));
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = (_a = workspace.getLeavesOfType(VIEW_TYPE_MILLER)[0]) != null ? _a : null;
    if (!leaf) {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE_MILLER, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
};
var MillerColumnsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Default column width").setDesc("Width in pixels for columns that have not been resized.").addSlider(
      (slider) => slider.setLimits(MIN_COLUMN_WIDTH, MAX_COLUMN_WIDTH, 10).setValue(this.plugin.settings.columnWidth).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.columnWidth = value;
        await this.plugin.saveSettings();
      })
    ).addExtraButton(
      (button) => button.setIcon("reset").setTooltip("Reset to default").onClick(async () => {
        this.plugin.settings.columnWidth = DEFAULT_SETTINGS.columnWidth;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Individual column widths").setDesc("Drag the right edge of any column to resize that column depth. Double-click the edge to reset it.").addButton(
      (button) => button.setButtonText("Reset all").onClick(async () => {
        this.plugin.settings.columnWidths = [];
        await this.plugin.saveSettings();
      })
    );
  }
};
