/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_MILLER: () => VIEW_TYPE_MILLER,
  default: () => MillerColumnsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_MILLER = "miller-columns-view";
var ICON_ID = "miller-columns";
var ICON_SVG = '<rect x="10" y="18" width="80" height="64" rx="8" fill="none" stroke="currentColor" stroke-width="8"/><line x1="37" y1="18" x2="37" y2="82" stroke="currentColor" stroke-width="8"/><line x1="63" y1="18" x2="63" y2="82" stroke="currentColor" stroke-width="8"/>';
var REFRESH_ALL = "*";
function compareNames(a, b) {
  return a.name.localeCompare(b.name, void 0, {
    sensitivity: "base",
    numeric: true
  });
}
function parentPathOf(path) {
  const idx = path.lastIndexOf("/");
  return idx <= 0 ? "/" : path.substring(0, idx);
}
function errorMessage(e) {
  return e instanceof Error ? e.message : String(e);
}
var MillerColumnsView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    /** selection[i] is the selected item in column i; only the last entry may be a file. */
    this.selection = [];
    this.activeColumn = 0;
    this.columns = [];
    this.affected = /* @__PURE__ */ new Set();
    this.refreshQueued = false;
    this.navigation = false;
  }
  getViewType() {
    return VIEW_TYPE_MILLER;
  }
  getDisplayText() {
    return "Miller Columns";
  }
  getIcon() {
    return ICON_ID;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("miller-columns");
    const header = contentEl.createDiv({ cls: "mc-header" });
    this.makeHeaderButton(
      header,
      "file-plus",
      "New note",
      () => this.createNote(this.deepestSelectedFolder())
    );
    this.makeHeaderButton(
      header,
      "folder-plus",
      "New folder",
      () => this.createFolder(this.deepestSelectedFolder())
    );
    this.columnsEl = contentEl.createDiv({ cls: "mc-columns" });
    this.columnsEl.setAttr("tabindex", "0");
    this.columnsEl.addEventListener("keydown", (e) => this.onKeyDown(e));
    this.registerEvent(
      this.app.vault.on("create", (f) => this.queueRefresh(this.parentsOf(f.path)))
    );
    this.registerEvent(
      this.app.vault.on("delete", (f) => this.queueRefresh(this.parentsOf(f.path)))
    );
    this.registerEvent(
      this.app.vault.on("rename", () => this.queueRefresh([REFRESH_ALL]))
    );
    this.buildColumnsFrom(0);
  }
  async onClose() {
    this.columns = [];
    this.contentEl.empty();
  }
  // ---------------------------------------------------------------- columns
  /** Number of columns implied by the current selection (root + one per selected folder). */
  columnCount() {
    let n = 1;
    for (const item of this.selection) {
      if (item instanceof import_obsidian.TFolder) n++;
      else break;
    }
    return n;
  }
  folderForColumn(i) {
    if (i === 0) return this.app.vault.getRoot();
    const sel = this.selection[i - 1];
    return sel instanceof import_obsidian.TFolder ? sel : null;
  }
  visibleChildren(folder) {
    const configDir = this.app.vault.configDir;
    return folder.children.filter((c) => c.path !== configDir);
  }
  itemsForColumn(i) {
    const col = this.columns[i];
    if (!col) return [];
    const children = this.visibleChildren(col.folder);
    const folders = children.filter((c) => c instanceof import_obsidian.TFolder).sort(compareNames);
    const files = children.filter((c) => c instanceof import_obsidian.TFile).sort(compareNames);
    return [...folders, ...files];
  }
  /** Remove columns from `index` on, then (re)create every column the selection implies. */
  buildColumnsFrom(index, scroll = true) {
    for (const col of this.columns.splice(index)) col.el.detach();
    const total = this.columnCount();
    for (let i = this.columns.length; i < total; i++) {
      const folder = this.folderForColumn(i);
      if (!folder) break;
      const el = this.columnsEl.createDiv({ cls: "mc-column" });
      this.columns.push({ folder, el });
      this.attachColumnHandlers(el, i);
      this.renderColumn(i);
    }
    this.updateSelectionClasses();
    if (scroll) this.scrollToNewestColumn();
  }
  renderColumn(i) {
    const col = this.columns[i];
    if (!col) return;
    col.el.empty();
    const items = this.itemsForColumn(i);
    if (items.length === 0) {
      col.el.createDiv({
        cls: "mc-empty",
        text: "No items. Right-click to create a note."
      });
      return;
    }
    for (const item of items) this.renderRow(col.el, i, item);
  }
  renderRow(colEl, colIndex, item) {
    const row = colEl.createDiv({ cls: "mc-item" });
    row.dataset.path = item.path;
    row.setAttr("draggable", "true");
    const iconEl = row.createSpan({ cls: "mc-icon" });
    (0, import_obsidian.setIcon)(iconEl, item instanceof import_obsidian.TFolder ? "folder" : "file-text");
    const displayName = item instanceof import_obsidian.TFile && item.extension === "md" ? item.basename : item.name;
    row.createSpan({ cls: "mc-name", text: displayName });
    if (item instanceof import_obsidian.TFolder) {
      row.createSpan({
        cls: "mc-count",
        text: String(this.visibleChildren(item).length)
      });
      row.createSpan({ cls: "mc-chevron", text: "\u203A" });
    }
    row.addEventListener("click", () => {
      this.columnsEl.focus({ preventScroll: true });
      this.selectItem(colIndex, item);
    });
    row.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.showItemMenu(e, item);
    });
    row.addEventListener("dragstart", (e) => {
      if (!e.dataTransfer) return;
      e.dataTransfer.setData("text/plain", item.path);
      e.dataTransfer.effectAllowed = "move";
    });
    if (item instanceof import_obsidian.TFolder) {
      this.addDropHandlers(row, () => item);
    }
  }
  attachColumnHandlers(el, index) {
    el.addEventListener("contextmenu", (e) => {
      if (e.target.closest(".mc-item")) return;
      e.preventDefault();
      const col = this.columns[index];
      if (col) this.showFolderMenu(e, col.folder);
    });
    this.addDropHandlers(el, () => {
      var _a, _b;
      return (_b = (_a = this.columns[index]) == null ? void 0 : _a.folder) != null ? _b : null;
    });
  }
  updateSelectionClasses() {
    const tipIndex = this.selection.length - 1;
    this.columns.forEach((col, i) => {
      const selPath = this.selection[i] ? this.selection[i].path : null;
      col.el.querySelectorAll(".mc-item").forEach((row) => {
        const selected = selPath !== null && row.dataset.path === selPath;
        row.classList.toggle("is-selected", selected);
        row.classList.toggle("is-active", selected && i === tipIndex);
      });
    });
  }
  scrollToNewestColumn() {
    window.requestAnimationFrame(() => {
      this.columnsEl.scrollLeft = this.columnsEl.scrollWidth;
    });
  }
  scrollRowIntoView(colIndex, path) {
    const col = this.columns[colIndex];
    if (!col) return;
    const rows = Array.from(col.el.querySelectorAll(".mc-item"));
    for (const row of rows) {
      if (row.dataset.path === path) {
        row.scrollIntoView({ block: "nearest" });
        return;
      }
    }
  }
  // -------------------------------------------------------------- selection
  selectItem(colIndex, item, openFile = true) {
    this.selection = this.selection.slice(0, colIndex);
    this.selection[colIndex] = item;
    this.activeColumn = colIndex;
    this.buildColumnsFrom(colIndex + 1);
    this.scrollRowIntoView(colIndex, item.path);
    if (openFile && item instanceof import_obsidian.TFile) {
      void this.app.workspace.getLeaf(false).openFile(item);
    }
  }
  deepestSelectedFolder() {
    let target = this.app.vault.getRoot();
    for (const item of this.selection) {
      if (item instanceof import_obsidian.TFolder) target = item;
      else break;
    }
    return target;
  }
  /** Select the full ancestor chain of `item` and rebuild all columns around it. */
  revealPath(item) {
    const chain = [];
    let cur = item;
    while (cur && cur.parent) {
      chain.unshift(cur);
      cur = cur.parent;
    }
    this.selection = chain;
    this.activeColumn = Math.max(0, chain.length - 1);
    this.buildColumnsFrom(0);
    if (chain.length > 0) this.scrollRowIntoView(chain.length - 1, item.path);
  }
  // --------------------------------------------------------------- keyboard
  onKeyDown(e) {
    if (this.columns.length === 0) return;
    const col = Math.min(this.activeColumn, this.columns.length - 1);
    this.activeColumn = col;
    const items = this.itemsForColumn(col);
    const current = this.selection[col];
    const idx = current ? items.indexOf(current) : -1;
    switch (e.key) {
      case "ArrowDown": {
        if (items.length === 0) break;
        const next = items[Math.min(items.length - 1, idx + 1)];
        this.selectItem(col, next, false);
        break;
      }
      case "ArrowUp": {
        if (items.length === 0) break;
        const next = items[idx === -1 ? items.length - 1 : Math.max(0, idx - 1)];
        this.selectItem(col, next, false);
        break;
      }
      case "ArrowLeft": {
        if (col > 0) this.activeColumn = col - 1;
        break;
      }
      case "ArrowRight": {
        this.descendIntoSelectedFolder(col);
        break;
      }
      case "Enter": {
        const sel = this.selection[col];
        if (sel instanceof import_obsidian.TFile) {
          void this.app.workspace.getLeaf(false).openFile(sel);
        } else if (sel instanceof import_obsidian.TFolder) {
          this.descendIntoSelectedFolder(col);
        }
        break;
      }
      default:
        return;
    }
    e.preventDefault();
  }
  descendIntoSelectedFolder(col) {
    const sel = this.selection[col];
    if (!(sel instanceof import_obsidian.TFolder) || this.columns.length <= col + 1) return;
    this.activeColumn = col + 1;
    if (!this.selection[col + 1]) {
      const childItems = this.itemsForColumn(col + 1);
      if (childItems.length > 0) this.selectItem(col + 1, childItems[0], false);
    }
  }
  // ------------------------------------------------------------ live update
  parentsOf(path) {
    const parent = parentPathOf(path);
    return [parent, parentPathOf(parent)];
  }
  queueRefresh(paths) {
    for (const p of paths) this.affected.add(p);
    if (this.refreshQueued) return;
    this.refreshQueued = true;
    window.setTimeout(() => {
      this.refreshQueued = false;
      const affected = this.affected;
      this.affected = /* @__PURE__ */ new Set();
      this.refresh(affected);
    }, 0);
  }
  refresh(affected) {
    let valid = 0;
    while (valid < this.selection.length) {
      const item = this.selection[valid];
      if (this.app.vault.getAbstractFileByPath(item.path) !== item) break;
      if (item.parent !== this.folderForColumn(valid)) break;
      valid++;
    }
    if (valid < this.selection.length) this.selection.length = valid;
    this.activeColumn = Math.min(this.activeColumn, this.columnCount() - 1);
    this.buildColumnsFrom(this.columnCount(), false);
    const all = affected.has(REFRESH_ALL);
    this.columns.forEach((col, i) => {
      if (all || affected.has(col.folder.path)) this.renderColumn(i);
    });
    this.updateSelectionClasses();
  }
  // ---------------------------------------------------------- file actions
  makeHeaderButton(parent, icon, label, onClick) {
    const btn = parent.createEl("button", { cls: "mc-btn" });
    const iconEl = btn.createSpan({ cls: "mc-btn-icon" });
    (0, import_obsidian.setIcon)(iconEl, icon);
    btn.createSpan({ text: label });
    btn.addEventListener("click", onClick);
  }
  showItemMenu(e, item) {
    var _a;
    const targetFolder = item instanceof import_obsidian.TFolder ? item : (_a = item.parent) != null ? _a : this.app.vault.getRoot();
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle("New note").setIcon("file-plus").onClick(() => this.createNote(targetFolder))
    );
    menu.addItem(
      (mi) => mi.setTitle("New folder").setIcon("folder-plus").onClick(() => this.createFolder(targetFolder))
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.app, item).open())
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Delete").setIcon("trash").onClick(async () => {
        try {
          await this.app.fileManager.trashFile(item);
        } catch (err) {
          new import_obsidian.Notice("Could not delete: " + errorMessage(err));
        }
      })
    );
    menu.showAtMouseEvent(e);
  }
  showFolderMenu(e, folder) {
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle("New note").setIcon("file-plus").onClick(() => this.createNote(folder))
    );
    menu.addItem(
      (mi) => mi.setTitle("New folder").setIcon("folder-plus").onClick(() => this.createFolder(folder))
    );
    menu.showAtMouseEvent(e);
  }
  uniquePath(folder, base, ext) {
    const prefix = folder.isRoot() ? "" : folder.path + "/";
    let candidate = base;
    let n = 1;
    while (this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(prefix + candidate + ext))) {
      candidate = `${base} ${n++}`;
    }
    return (0, import_obsidian.normalizePath)(prefix + candidate + ext);
  }
  async createNote(folder) {
    try {
      const path = this.uniquePath(folder, "Untitled", ".md");
      const file = await this.app.vault.create(path, "");
      this.revealPath(file);
      await this.app.workspace.getLeaf(false).openFile(file);
    } catch (e) {
      new import_obsidian.Notice("Could not create note: " + errorMessage(e));
    }
  }
  async createFolder(parent) {
    try {
      const path = this.uniquePath(parent, "New folder", "");
      const folder = await this.app.vault.createFolder(path);
      this.revealPath(folder);
    } catch (e) {
      new import_obsidian.Notice("Could not create folder: " + errorMessage(e));
    }
  }
  // ------------------------------------------------------------ drag & drop
  addDropHandlers(el, getFolder) {
    el.addEventListener("dragover", (e) => {
      if (!e.dataTransfer || !e.dataTransfer.types.includes("text/plain")) return;
      e.preventDefault();
      e.stopPropagation();
      e.dataTransfer.dropEffect = "move";
      el.addClass("mc-drop-target");
    });
    el.addEventListener("dragleave", () => el.removeClass("mc-drop-target"));
    el.addEventListener("drop", (e) => {
      var _a;
      el.removeClass("mc-drop-target");
      const path = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!path) return;
      e.preventDefault();
      e.stopPropagation();
      const src = this.app.vault.getAbstractFileByPath(path);
      const target = getFolder();
      if (src && target) void this.moveInto(src, target);
    });
  }
  async moveInto(src, target) {
    if (src === target || src.parent === target) return;
    if (src instanceof import_obsidian.TFolder && (target === src || target.path.startsWith(src.path + "/"))) {
      new import_obsidian.Notice("Cannot move a folder into itself.");
      return;
    }
    const dest = (0, import_obsidian.normalizePath)((target.isRoot() ? "" : target.path + "/") + src.name);
    if (this.app.vault.getAbstractFileByPath(dest)) {
      new import_obsidian.Notice("An item with that name already exists there.");
      return;
    }
    try {
      await this.app.fileManager.renameFile(src, dest);
    } catch (e) {
      new import_obsidian.Notice("Could not move: " + errorMessage(e));
    }
  }
};
var RenameModal = class extends import_obsidian.Modal {
  constructor(app, item) {
    super(app);
    this.item = item;
  }
  onOpen() {
    this.titleEl.setText(this.item instanceof import_obsidian.TFolder ? "Rename folder" : "Rename file");
    const input = this.contentEl.createEl("input", {
      cls: "mc-rename-input",
      type: "text",
      value: this.item.name
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void this.submit(input.value);
      }
    });
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Rename").setCta().onClick(() => void this.submit(input.value))
    );
    input.focus();
    if (this.item instanceof import_obsidian.TFile && this.item.extension) {
      input.setSelectionRange(0, Math.max(0, this.item.name.length - this.item.extension.length - 1));
    } else {
      input.select();
    }
  }
  async submit(name) {
    name = name.trim();
    if (!name || name.includes("/") || name.includes("\\")) {
      new import_obsidian.Notice("Invalid name.");
      return;
    }
    const parent = this.item.parent;
    const prefix = parent && !parent.isRoot() ? parent.path + "/" : "";
    try {
      await this.app.fileManager.renameFile(this.item, (0, import_obsidian.normalizePath)(prefix + name));
      this.close();
    } catch (e) {
      new import_obsidian.Notice("Rename failed: " + errorMessage(e));
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MillerColumnsPlugin = class extends import_obsidian.Plugin {
  async onload() {
    (0, import_obsidian.addIcon)(ICON_ID, ICON_SVG);
    this.registerView(VIEW_TYPE_MILLER, (leaf) => new MillerColumnsView(leaf));
    this.addRibbonIcon(ICON_ID, "Open Miller Columns", () => void this.activateView());
    this.addCommand({
      id: "open",
      name: "Open",
      callback: () => void this.activateView()
    });
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = (_a = workspace.getLeavesOfType(VIEW_TYPE_MILLER)[0]) != null ? _a : null;
    if (!leaf) {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE_MILLER, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
};
