/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_MILLER: () => VIEW_TYPE_MILLER,
  default: () => MillerColumnsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_MILLER = "miller-columns-view";
var ICON_ID = "miller-columns";
var ICON_SVG = '<rect x="10" y="18" width="80" height="64" rx="8" fill="none" stroke="currentColor" stroke-width="8"/><line x1="37" y1="18" x2="37" y2="82" stroke="currentColor" stroke-width="8"/><line x1="63" y1="18" x2="63" y2="82" stroke="currentColor" stroke-width="8"/>';
var REFRESH_ALL = "*";
var SUBPAGE_BLOCK_START = "<!-- miller-columns-subpages:start -->";
var SUBPAGE_BLOCK_END = "<!-- miller-columns-subpages:end -->";
var MIN_COLUMN_WIDTH = 64;
var COMPACT_COLUMN_WIDTH = 96;
var MAX_COLUMN_WIDTH = 520;
var DEFAULT_SETTINGS = {
  columnWidth: 220,
  columnWidths: [],
  appearances: {},
  pinnedPaths: [],
  shortcuts: []
};
var DEFAULT_PAGE_ICON = "file-text";
var ICON_PRESETS = ["file-text", "book-open", "notebook", "library", "folder", "star", "bookmark", "lightbulb", "pen-line"];
var COLOR_PRESETS = ["", "#e06c75", "#d19a66", "#e5c07b", "#98c379", "#56b6c2", "#61afef", "#c678dd"];
function compareNames(a, b) {
  return a.name.localeCompare(b.name, void 0, {
    sensitivity: "base",
    numeric: true
  });
}
function parentPathOf(path) {
  const idx = path.lastIndexOf("/");
  return idx <= 0 ? "/" : path.substring(0, idx);
}
function errorMessage(e) {
  return e instanceof Error ? e.message : String(e);
}
function markdownLinkPath(file) {
  return file.path.replace(/\.md$/i, "");
}
function markdownPageLink(file) {
  return `[[${markdownLinkPath(file)}|${file.basename}]]`;
}
function normalizeTag(tag) {
  return tag.trim().replace(/^#+/, "");
}
function parseTagInput(value) {
  const tags = [];
  const seen = /* @__PURE__ */ new Set();
  for (const part of value.split(/[,\s]+/)) {
    const tag = normalizeTag(part);
    if (!tag || seen.has(tag)) continue;
    seen.add(tag);
    tags.push(tag);
  }
  return tags;
}
function frontmatterTags(value) {
  if (Array.isArray(value)) {
    return value.flatMap((tag) => frontmatterTags(tag));
  }
  if (typeof value === "string") {
    return parseTagInput(value);
  }
  return [];
}
var MillerColumnsView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    /** selection[i] is the selected item in column i; only the last entry may be a file. */
    this.selection = [];
    this.activeTag = null;
    this.tagSelection = null;
    this.activeColumn = 0;
    this.columns = [];
    this.affected = /* @__PURE__ */ new Set();
    this.refreshQueued = false;
    this.navigation = false;
  }
  getViewType() {
    return VIEW_TYPE_MILLER;
  }
  getDisplayText() {
    return "Miller Columns";
  }
  getIcon() {
    return ICON_ID;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("miller-columns");
    this.applySettings();
    this.columnsEl = contentEl.createDiv({ cls: "mc-columns" });
    this.columnsEl.setAttr("tabindex", "0");
    this.columnsEl.addEventListener("keydown", (e) => this.onKeyDown(e));
    this.registerEvent(
      this.app.vault.on("create", (f) => this.queueRefresh(this.parentsOf(f.path)))
    );
    this.registerEvent(
      this.app.vault.on("delete", (f) => this.queueRefresh(this.parentsOf(f.path)))
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        const refresh = () => this.queueRefresh([REFRESH_ALL]);
        void this.plugin.handleVaultRename(file, oldPath).then(refresh, refresh);
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", () => this.queueRefresh([REFRESH_ALL]))
    );
    this.buildColumnsFrom(0);
  }
  async onClose() {
    this.columns = [];
    this.contentEl.empty();
  }
  applySettings() {
    this.contentEl.style.setProperty(
      "--mc-column-width",
      `${this.plugin.settings.columnWidth}px`
    );
    this.columns.forEach((col, i) => this.applyColumnWidth(col.el, i));
  }
  refreshNavigation() {
    this.queueRefresh([REFRESH_ALL]);
  }
  // ---------------------------------------------------------------- columns
  /** Number of columns implied by the current selection (root + one per selected folder). */
  columnCount() {
    if (this.activeTag !== null) return 2;
    let n = 1;
    for (const item of this.selection) {
      if (item instanceof import_obsidian.TFolder) n++;
      else break;
    }
    return n;
  }
  folderForColumn(i) {
    if (this.activeTag !== null && i > 0) return null;
    if (i === 0) return this.app.vault.getRoot();
    const sel = this.selection[i - 1];
    return sel instanceof import_obsidian.TFolder ? sel : null;
  }
  folderPagePath(folder) {
    if (folder.isRoot()) return null;
    return (0, import_obsidian.normalizePath)(`${folder.path}/${folder.name}.md`);
  }
  isFolderPage(folder, item) {
    const pagePath = this.folderPagePath(folder);
    return pagePath !== null && item instanceof import_obsidian.TFile && item.path === pagePath;
  }
  visibleChildren(folder) {
    const configDir = this.app.vault.configDir;
    return folder.children.filter((c) => c.path !== configDir && !this.isFolderPage(folder, c));
  }
  sourceForColumn(i) {
    if (i === 0) return { kind: "folder", folder: this.app.vault.getRoot() };
    if (this.activeTag !== null && i === 1) return { kind: "tag", tag: this.activeTag };
    const folder = this.folderForColumn(i);
    return folder ? { kind: "folder", folder } : null;
  }
  sortAndPin(items) {
    const folders = items.filter((item) => item instanceof import_obsidian.TFolder).sort(compareNames);
    const files = items.filter((item) => item instanceof import_obsidian.TFile).sort(compareNames);
    const sorted = [...folders, ...files];
    return [
      ...sorted.filter((item) => this.plugin.isPinned(item.path)),
      ...sorted.filter((item) => !this.plugin.isPinned(item.path))
    ];
  }
  itemsForColumn(i) {
    const col = this.columns[i];
    if (!col) return [];
    if (col.source.kind === "tag") return this.filesForTag(col.source.tag);
    return this.sortAndPin(this.visibleChildren(col.source.folder));
  }
  /** Remove columns from `index` on, then (re)create every column the selection implies. */
  buildColumnsFrom(index, scroll = true) {
    for (const col of this.columns.splice(index)) col.el.detach();
    const total = this.columnCount();
    for (let i = this.columns.length; i < total; i++) {
      const source = this.sourceForColumn(i);
      if (!source) break;
      const el = this.columnsEl.createDiv({ cls: "mc-column" });
      this.columns.push({ source, el });
      this.applyColumnWidth(el, i);
      this.attachColumnHandlers(el, i);
      this.renderColumn(i);
    }
    this.updateSelectionClasses();
    if (scroll) this.scrollToNewestColumn();
  }
  renderColumn(i) {
    const col = this.columns[i];
    if (!col) return;
    col.el.empty();
    if (col.source.kind === "tag") {
      this.renderTagResults(col.el, i, col.source.tag);
    } else {
      this.renderFolderColumn(col.el, i, col.source.folder);
    }
    this.renderResizeHandle(col.el, i);
  }
  renderFolderColumn(colEl, colIndex, folder) {
    const items = this.itemsForColumn(colIndex);
    const pinned = items.filter((item) => this.plugin.isPinned(item.path));
    const normal = items.filter((item) => !this.plugin.isPinned(item.path));
    if (folder.isRoot()) {
      this.renderSectionHeader(colEl, "Shortcuts", "star");
      this.renderShortcuts(colEl, colIndex);
    }
    if (pinned.length > 0) {
      this.renderSectionHeader(colEl, "Pinned", "pin");
      for (const item of pinned) this.renderRow(colEl, colIndex, item);
    }
    if (folder.isRoot() || pinned.length > 0) {
      this.renderSectionHeader(colEl, folder.isRoot() ? "Vault" : "Pages", "folder-tree");
    }
    if (normal.length > 0) {
      for (const item of normal) this.renderRow(colEl, colIndex, item);
    } else if (pinned.length === 0) {
      colEl.createDiv({
        cls: "mc-section-empty",
        text: "No pages. Right-click to create one."
      });
    }
    if (folder.isRoot()) {
      this.renderSectionHeader(colEl, "Tags", "tags");
      const tags = this.tagEntries();
      if (tags.length === 0) {
        colEl.createDiv({ cls: "mc-section-empty", text: "No tags yet." });
      } else {
        for (const entry of tags) this.renderTagRow(colEl, entry);
      }
    }
  }
  renderTagResults(colEl, colIndex, tag) {
    this.renderSectionHeader(colEl, `#${tag}`, "tag");
    const items = this.filesForTag(tag);
    const pinned = items.filter((item) => this.plugin.isPinned(item.path));
    const normal = items.filter((item) => !this.plugin.isPinned(item.path));
    if (pinned.length > 0) {
      this.renderSectionHeader(colEl, "Pinned", "pin");
      for (const item of pinned) {
        this.renderRow(colEl, colIndex, item, () => this.selectTagResult(item));
      }
    }
    if (pinned.length > 0 && normal.length > 0) {
      this.renderSectionHeader(colEl, "Results", "files");
    }
    for (const item of normal) {
      this.renderRow(colEl, colIndex, item, () => this.selectTagResult(item));
    }
    if (items.length === 0) {
      colEl.createDiv({ cls: "mc-empty", text: `No pages tagged #${tag}.` });
    }
  }
  renderSectionHeader(colEl, title, icon) {
    const header = colEl.createDiv({ cls: "mc-section-header" });
    const iconEl = header.createSpan({ cls: "mc-section-icon" });
    (0, import_obsidian.setIcon)(iconEl, icon);
    header.createSpan({ text: title });
  }
  renderShortcuts(colEl, colIndex) {
    if (this.plugin.settings.shortcuts.length === 0) {
      colEl.createDiv({ cls: "mc-section-empty", text: "Add shortcuts from an item menu." });
      return;
    }
    let rendered = 0;
    for (const shortcut of this.plugin.settings.shortcuts) {
      if (shortcut.type === "path") {
        const item = this.app.vault.getAbstractFileByPath(shortcut.value);
        if (!item) continue;
        const row = this.renderRow(colEl, colIndex, item, () => this.openShortcut(item));
        row.addClass("mc-shortcut");
        row.dataset.shortcut = "true";
        rendered++;
      } else {
        this.renderTagRow(colEl, {
          tag: shortcut.value,
          count: this.filesForTag(shortcut.value).length
        }, true);
        rendered++;
      }
    }
    if (rendered === 0) {
      colEl.createDiv({ cls: "mc-section-empty", text: "No available shortcuts." });
    }
  }
  renderTagRow(colEl, entry, shortcut = false) {
    const row = colEl.createDiv({ cls: "mc-item mc-tag-item" });
    row.dataset.tag = entry.tag;
    if (shortcut) {
      row.addClass("mc-shortcut");
      row.dataset.shortcut = "true";
    } else {
      row.style.setProperty("--mc-tag-depth", String(entry.tag.split("/").length - 1));
    }
    const iconEl = row.createSpan({ cls: "mc-icon" });
    (0, import_obsidian.setIcon)(iconEl, shortcut ? "star" : "tag");
    row.createSpan({ cls: "mc-name", text: `#${entry.tag}` });
    row.createSpan({ cls: "mc-count", text: String(entry.count) });
    row.createSpan({ cls: "mc-chevron", text: "\u203A" });
    row.addEventListener("click", () => {
      this.columnsEl.focus({ preventScroll: true });
      this.selectTag(entry.tag);
    });
    row.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.showTagMenu(e, entry.tag);
    });
  }
  tagEntries() {
    var _a;
    const counts = /* @__PURE__ */ new Map();
    for (const file of this.app.vault.getMarkdownFiles()) {
      const tags = /* @__PURE__ */ new Set();
      for (const tag of this.tagsForFile(file)) {
        const parts = tag.split("/");
        for (let i = 1; i <= parts.length; i++) tags.add(parts.slice(0, i).join("/"));
      }
      for (const tag of tags) counts.set(tag, ((_a = counts.get(tag)) != null ? _a : 0) + 1);
    }
    return Array.from(counts, ([tag, count]) => ({ tag, count })).sort(
      (a, b) => a.tag.localeCompare(b.tag, void 0, { sensitivity: "base", numeric: true })
    );
  }
  tagsForFile(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache) return [];
    return ((_a = (0, import_obsidian.getAllTags)(cache)) != null ? _a : []).map(normalizeTag).filter(Boolean);
  }
  filesForTag(tag) {
    const matches = this.app.vault.getMarkdownFiles().filter(
      (file) => this.tagsForFile(file).some((candidate) => candidate === tag || candidate.startsWith(tag + "/"))
    );
    matches.sort(compareNames);
    return [
      ...matches.filter((file) => this.plugin.isPinned(file.path)),
      ...matches.filter((file) => !this.plugin.isPinned(file.path))
    ];
  }
  applyColumnWidth(el, index) {
    const width = this.plugin.columnWidthFor(index);
    el.style.setProperty("--mc-column-width", `${width}px`);
    el.toggleClass("is-narrow", width < COMPACT_COLUMN_WIDTH);
  }
  renderResizeHandle(colEl, colIndex) {
    const handle = colEl.createDiv({ cls: "mc-resize-handle" });
    handle.setAttr("aria-label", "Resize column");
    handle.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const startX = e.clientX;
      const startWidth = this.plugin.columnWidthFor(colIndex);
      handle.addClass("is-resizing");
      const onMove = (moveEvent) => {
        const width = this.plugin.setColumnWidth(
          colIndex,
          startWidth + moveEvent.clientX - startX
        );
        this.applyColumnWidth(colEl, colIndex);
        colEl.style.setProperty("--mc-column-width", `${width}px`);
      };
      const onUp = () => {
        handle.removeClass("is-resizing");
        window.removeEventListener("pointermove", onMove);
        window.removeEventListener("pointerup", onUp);
        void this.plugin.saveSettings();
      };
      window.addEventListener("pointermove", onMove);
      window.addEventListener("pointerup", onUp);
    });
    handle.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
    });
    handle.addEventListener("dblclick", async (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.plugin.resetColumnWidth(colIndex);
      this.applyColumnWidth(colEl, colIndex);
      await this.plugin.saveSettings();
    });
  }
  renderRow(colEl, colIndex, item, onSelect) {
    var _a;
    const row = colEl.createDiv({ cls: "mc-item" });
    row.dataset.path = item.path;
    row.setAttr("title", item.path);
    row.setAttr("draggable", "true");
    const iconEl = row.createSpan({ cls: "mc-icon" });
    const appearance = this.plugin.appearanceFor(item.path);
    (0, import_obsidian.setIcon)(iconEl, (_a = appearance.icon) != null ? _a : DEFAULT_PAGE_ICON);
    if (appearance.color) iconEl.style.color = appearance.color;
    const displayName = item instanceof import_obsidian.TFile && item.extension === "md" ? item.basename : item.name;
    row.createSpan({ cls: "mc-name", text: displayName });
    if (item instanceof import_obsidian.TFolder) {
      row.createSpan({ cls: "mc-chevron", text: "\u203A" });
    }
    row.addEventListener("click", () => {
      this.columnsEl.focus({ preventScroll: true });
      if (onSelect) onSelect();
      else this.selectItem(colIndex, item);
    });
    row.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.showItemMenu(e, item);
    });
    row.addEventListener("dragstart", (e) => {
      if (!e.dataTransfer) return;
      e.dataTransfer.setData("text/plain", item.path);
      e.dataTransfer.effectAllowed = "move";
    });
    if (item instanceof import_obsidian.TFolder) {
      this.addDropHandlers(row, () => item);
    }
    return row;
  }
  attachColumnHandlers(el, index) {
    el.addEventListener("contextmenu", (e) => {
      if (e.target.closest(".mc-item")) return;
      e.preventDefault();
      const col = this.columns[index];
      if ((col == null ? void 0 : col.source.kind) === "folder") this.showFolderMenu(e, col.source.folder);
    });
    this.addDropHandlers(el, () => {
      var _a;
      const source = (_a = this.columns[index]) == null ? void 0 : _a.source;
      return (source == null ? void 0 : source.kind) === "folder" ? source.folder : null;
    });
  }
  updateSelectionClasses() {
    this.columns.forEach((col, i) => {
      col.el.querySelectorAll(".mc-item").forEach((row) => {
        var _a, _b;
        let selected = false;
        if (row.dataset.shortcut !== "true") {
          if (row.dataset.tag) {
            selected = this.activeTag === row.dataset.tag;
          } else if (col.source.kind === "tag") {
            selected = ((_a = this.tagSelection) == null ? void 0 : _a.path) === row.dataset.path;
          } else {
            selected = ((_b = this.selection[i]) == null ? void 0 : _b.path) === row.dataset.path;
          }
        }
        row.classList.toggle("is-selected", selected);
        row.classList.toggle("is-active", selected && i === this.activeColumn);
      });
    });
  }
  scrollToNewestColumn() {
    window.requestAnimationFrame(() => {
      this.columnsEl.scrollLeft = this.columnsEl.scrollWidth;
    });
  }
  scrollRowIntoView(colIndex, path) {
    const col = this.columns[colIndex];
    if (!col) return;
    const rows = Array.from(col.el.querySelectorAll(".mc-item"));
    for (const row of rows) {
      if (row.dataset.path === path) {
        row.scrollIntoView({ block: "nearest" });
        return;
      }
    }
  }
  // -------------------------------------------------------------- selection
  selectItem(colIndex, item, openFile = true) {
    this.activeTag = null;
    this.tagSelection = null;
    this.selection = this.selection.slice(0, colIndex);
    this.selection[colIndex] = item;
    this.activeColumn = colIndex;
    this.buildColumnsFrom(colIndex + 1);
    this.scrollRowIntoView(colIndex, item.path);
    if (openFile && item instanceof import_obsidian.TFile) {
      void this.openPageFile(item);
    } else if (openFile && item instanceof import_obsidian.TFolder) {
      void this.openFolderPage(item);
    }
  }
  /** Select the full ancestor chain of `item` and rebuild all columns around it. */
  revealPath(item) {
    this.activeTag = null;
    this.tagSelection = null;
    const chain = [];
    let cur = item;
    while (cur && cur.parent) {
      chain.unshift(cur);
      cur = cur.parent;
    }
    this.selection = chain;
    this.activeColumn = Math.max(0, chain.length - 1);
    this.buildColumnsFrom(0);
    if (chain.length > 0) this.scrollRowIntoView(chain.length - 1, item.path);
  }
  openShortcut(item) {
    this.revealPath(item);
    if (item instanceof import_obsidian.TFile) void this.openPageFile(item);
    else if (item instanceof import_obsidian.TFolder) void this.openFolderPage(item);
  }
  selectTag(tag) {
    this.selection = [];
    this.activeTag = tag;
    this.tagSelection = null;
    this.activeColumn = 1;
    this.buildColumnsFrom(0);
  }
  selectTagResult(file, openFile = true) {
    this.tagSelection = file;
    this.activeColumn = 1;
    this.updateSelectionClasses();
    this.scrollRowIntoView(1, file.path);
    if (openFile) void this.openPageFile(file);
  }
  // --------------------------------------------------------------- keyboard
  onKeyDown(e) {
    var _a;
    if (this.columns.length === 0) return;
    const col = Math.min(this.activeColumn, this.columns.length - 1);
    this.activeColumn = col;
    const items = this.itemsForColumn(col);
    const isTagColumn = ((_a = this.columns[col]) == null ? void 0 : _a.source.kind) === "tag";
    const current = isTagColumn ? this.tagSelection : this.selection[col];
    const idx = current ? items.indexOf(current) : -1;
    switch (e.key) {
      case "ArrowDown": {
        if (items.length === 0) break;
        const next = items[Math.min(items.length - 1, idx + 1)];
        if (isTagColumn && next instanceof import_obsidian.TFile) this.selectTagResult(next, false);
        else this.selectItem(col, next, false);
        break;
      }
      case "ArrowUp": {
        if (items.length === 0) break;
        const next = items[idx === -1 ? items.length - 1 : Math.max(0, idx - 1)];
        if (isTagColumn && next instanceof import_obsidian.TFile) this.selectTagResult(next, false);
        else this.selectItem(col, next, false);
        break;
      }
      case "ArrowLeft": {
        if (col > 0) this.activeColumn = col - 1;
        break;
      }
      case "ArrowRight": {
        this.descendIntoSelectedFolder(col);
        break;
      }
      case "Enter": {
        const sel = isTagColumn ? this.tagSelection : this.selection[col];
        if (sel instanceof import_obsidian.TFile) {
          void this.openPageFile(sel);
        } else if (sel instanceof import_obsidian.TFolder) {
          void this.openFolderPage(sel);
        }
        break;
      }
      default:
        return;
    }
    e.preventDefault();
  }
  descendIntoSelectedFolder(col) {
    const sel = this.selection[col];
    if (!(sel instanceof import_obsidian.TFolder) || this.columns.length <= col + 1) return;
    this.activeColumn = col + 1;
    if (!this.selection[col + 1]) {
      const childItems = this.itemsForColumn(col + 1);
      if (childItems.length > 0) this.selectItem(col + 1, childItems[0], false);
    }
  }
  // ------------------------------------------------------------ live update
  parentsOf(path) {
    const parent = parentPathOf(path);
    return [parent, parentPathOf(parent)];
  }
  queueRefresh(paths) {
    for (const p of paths) this.affected.add(p);
    if (this.refreshQueued) return;
    this.refreshQueued = true;
    window.setTimeout(() => {
      this.refreshQueued = false;
      const affected = this.affected;
      this.affected = /* @__PURE__ */ new Set();
      this.refresh(affected);
    }, 0);
  }
  refresh(affected) {
    let valid = 0;
    while (valid < this.selection.length) {
      const item = this.selection[valid];
      if (this.app.vault.getAbstractFileByPath(item.path) !== item) break;
      if (item.parent !== this.folderForColumn(valid)) break;
      valid++;
    }
    if (valid < this.selection.length) this.selection.length = valid;
    if (this.tagSelection && this.app.vault.getAbstractFileByPath(this.tagSelection.path) !== this.tagSelection) {
      this.tagSelection = null;
    }
    this.activeColumn = Math.min(this.activeColumn, this.columnCount() - 1);
    this.buildColumnsFrom(this.columnCount(), false);
    const all = affected.has(REFRESH_ALL);
    this.columns.forEach((col, i) => {
      if (all || col.source.kind === "tag" || col.source.kind === "folder" && affected.has(col.source.folder.path)) {
        this.renderColumn(i);
        if (col.source.kind === "folder") void this.syncFolderPage(col.source.folder);
      }
    });
    this.updateSelectionClasses();
  }
  // ---------------------------------------------------------- page content
  async openFolderPage(folder) {
    try {
      const page = await this.ensureFolderPage(folder);
      if (!page) return;
      await this.syncFolderPage(folder, page);
      if (folder.parent) await this.syncFolderPage(folder.parent);
      await this.openPageFile(page);
    } catch (e) {
      new import_obsidian.Notice("Could not open page: " + errorMessage(e));
    }
  }
  async openPageFile(file) {
    var _a;
    const { workspace } = this.app;
    const leaf = (_a = workspace.getMostRecentLeaf(workspace.rootSplit)) != null ? _a : workspace.getLeaf(false);
    await leaf.openFile(file, { state: { mode: "preview" } });
    workspace.setActiveLeaf(leaf, { focus: true });
  }
  async ensureFolderPage(folder) {
    const path = this.folderPagePath(folder);
    if (!path) return null;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFile) return existing;
    if (existing) {
      new import_obsidian.Notice(`Could not create page because ${path} already exists.`);
      return null;
    }
    return await this.app.vault.create(path, this.subpageBlock(folder));
  }
  async syncFolderPage(folder, knownPage) {
    if (folder.isRoot()) return;
    try {
      const pagePath = this.folderPagePath(folder);
      const existing = pagePath ? this.app.vault.getAbstractFileByPath(pagePath) : null;
      const page = knownPage != null ? knownPage : existing instanceof import_obsidian.TFile ? existing : null;
      if (!(page instanceof import_obsidian.TFile)) return;
      const block = this.subpageBlock(folder);
      const raw = await this.app.vault.read(page);
      const current = this.stripGeneratedTitle(raw, folder);
      const next = this.replaceSubpageBlock(current, block);
      if (next !== raw) await this.app.vault.modify(page, next);
    } catch (e) {
      new import_obsidian.Notice("Could not update subpage links: " + errorMessage(e));
    }
  }
  subpageBlock(folder) {
    const links = this.subpageFiles(folder).map((file) => `- ${markdownPageLink(file)}`);
    const body = links.length > 0 ? `${links.join("\n")}
` : "";
    return `${SUBPAGE_BLOCK_START}
${body}${SUBPAGE_BLOCK_END}`;
  }
  subpageFiles(folder) {
    const files = [];
    for (const child of this.visibleChildren(folder)) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        files.push(child);
      }
      if (child instanceof import_obsidian.TFolder) {
        const pagePath = this.folderPagePath(child);
        const page = pagePath ? this.app.vault.getAbstractFileByPath(pagePath) : null;
        if (page instanceof import_obsidian.TFile) files.push(page);
      }
    }
    return files.sort(compareNames);
  }
  replaceSubpageBlock(content, block) {
    const start = content.indexOf(SUBPAGE_BLOCK_START);
    const end = content.indexOf(SUBPAGE_BLOCK_END);
    if (start >= 0 && end >= start) {
      const afterEnd = end + SUBPAGE_BLOCK_END.length;
      return content.substring(0, start) + block + content.substring(afterEnd);
    }
    const trimmed = content.trimEnd();
    return `${trimmed}${trimmed ? "\n\n" : ""}${block}`;
  }
  stripGeneratedTitle(content, folder) {
    const heading = `# ${folder.name}`;
    const trimmedStart = content.trimStart();
    if (trimmedStart !== heading && !trimmedStart.startsWith(`${heading}
`)) return content;
    const leadingWhitespaceLength = content.length - trimmedStart.length;
    const afterHeading = trimmedStart.substring(heading.length);
    if (!/^\s*\n\s*\n?<!-- miller-columns-subpages:start -->/.test(afterHeading)) {
      return content;
    }
    return content.substring(0, leadingWhitespaceLength) + afterHeading.trimStart();
  }
  // ---------------------------------------------------------- file actions
  showItemMenu(e, item) {
    var _a;
    const targetFolder = item instanceof import_obsidian.TFolder ? item : (_a = item.parent) != null ? _a : this.app.vault.getRoot();
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle("New page").setIcon("file-plus").onClick(() => this.createPage(targetFolder))
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Icon and color").setIcon("palette").onClick(() => new AppearanceModal(this.app, this.plugin, item, () => this.refreshPath(item)).open())
    );
    menu.addItem(
      (mi) => mi.setTitle("Tags").setIcon("tags").onClick(() => void this.openTagsModal(item))
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle(this.plugin.isPinned(item.path) ? "Unpin" : "Pin").setIcon("pin").onClick(() => void this.plugin.togglePinned(item.path))
    );
    menu.addItem(
      (mi) => mi.setTitle(
        this.plugin.hasShortcut("path", item.path) ? "Remove shortcut" : "Add shortcut"
      ).setIcon("star").onClick(() => void this.plugin.toggleShortcut("path", item.path))
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.app, this.plugin, item).open())
    );
    menu.addSeparator();
    menu.addItem(
      (mi) => mi.setTitle("Delete").setIcon("trash").onClick(async () => {
        try {
          await this.app.fileManager.trashFile(item);
        } catch (err) {
          new import_obsidian.Notice("Could not delete: " + errorMessage(err));
        }
      })
    );
    menu.showAtMouseEvent(e);
  }
  showTagMenu(e, tag) {
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle(
        this.plugin.hasShortcut("tag", tag) ? "Remove shortcut" : "Add shortcut"
      ).setIcon("star").onClick(() => void this.plugin.toggleShortcut("tag", tag))
    );
    menu.showAtMouseEvent(e);
  }
  async openTagsModal(item) {
    const file = await this.pageFileForTags(item);
    if (!file) return;
    new TagsModal(this.app, file).open();
  }
  async pageFileForTags(item) {
    if (item instanceof import_obsidian.TFile) {
      if (item.extension === "md") return item;
      new import_obsidian.Notice("Tags can only be edited on Markdown pages.");
      return null;
    }
    if (item instanceof import_obsidian.TFolder) {
      try {
        return await this.ensureFolderPage(item);
      } catch (e) {
        new import_obsidian.Notice("Could not open page tags: " + errorMessage(e));
      }
    }
    return null;
  }
  refreshPath(item) {
    var _a;
    const parent = (_a = item.parent) != null ? _a : this.app.vault.getRoot();
    this.queueRefresh([parent.path]);
  }
  showFolderMenu(e, folder) {
    const menu = new import_obsidian.Menu();
    menu.addItem(
      (mi) => mi.setTitle("New page").setIcon("file-plus").onClick(() => this.createPage(folder))
    );
    menu.showAtMouseEvent(e);
  }
  uniquePath(folder, base, ext) {
    const prefix = folder.isRoot() ? "" : folder.path + "/";
    let candidate = base;
    let n = 1;
    while (this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(prefix + candidate + ext))) {
      candidate = `${base} ${n++}`;
    }
    return (0, import_obsidian.normalizePath)(prefix + candidate + ext);
  }
  async createPage(parent) {
    try {
      const path = this.uniquePath(parent, "Untitled", "");
      const folder = await this.app.vault.createFolder(path);
      const page = await this.ensureFolderPage(folder);
      if (page) await this.syncFolderPage(folder, page);
      await this.syncFolderPage(parent);
      this.revealPath(folder);
      if (page) await this.openPageFile(page);
    } catch (e) {
      new import_obsidian.Notice("Could not create page: " + errorMessage(e));
    }
  }
  // ------------------------------------------------------------ drag & drop
  addDropHandlers(el, getFolder) {
    el.addEventListener("dragover", (e) => {
      if (!e.dataTransfer || !e.dataTransfer.types.includes("text/plain")) return;
      e.preventDefault();
      e.stopPropagation();
      e.dataTransfer.dropEffect = "move";
      el.addClass("mc-drop-target");
    });
    el.addEventListener("dragleave", () => el.removeClass("mc-drop-target"));
    el.addEventListener("drop", (e) => {
      var _a;
      el.removeClass("mc-drop-target");
      const path = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!path) return;
      e.preventDefault();
      e.stopPropagation();
      const src = this.app.vault.getAbstractFileByPath(path);
      const target = getFolder();
      if (src && target) void this.moveInto(src, target);
    });
  }
  async moveInto(src, target) {
    if (src === target || src.parent === target) return;
    if (src instanceof import_obsidian.TFolder && (target === src || target.path.startsWith(src.path + "/"))) {
      new import_obsidian.Notice("Cannot move a folder into itself.");
      return;
    }
    const dest = (0, import_obsidian.normalizePath)((target.isRoot() ? "" : target.path + "/") + src.name);
    if (this.app.vault.getAbstractFileByPath(dest)) {
      new import_obsidian.Notice("An item with that name already exists there.");
      return;
    }
    try {
      await this.app.fileManager.renameFile(src, dest);
    } catch (e) {
      new import_obsidian.Notice("Could not move: " + errorMessage(e));
    }
  }
};
var RenameModal = class extends import_obsidian.Modal {
  constructor(app, plugin, item) {
    super(app);
    this.plugin = plugin;
    this.item = item;
  }
  onOpen() {
    this.titleEl.setText("Rename page");
    const input = this.contentEl.createEl("input", {
      cls: "mc-rename-input",
      type: "text",
      value: this.item.name
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void this.submit(input.value);
      }
    });
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Rename").setCta().onClick(() => void this.submit(input.value))
    );
    input.focus();
    if (this.item instanceof import_obsidian.TFile && this.item.extension) {
      input.setSelectionRange(0, Math.max(0, this.item.name.length - this.item.extension.length - 1));
    } else {
      input.select();
    }
  }
  async submit(name) {
    name = name.trim();
    if (!name || name.includes("/") || name.includes("\\")) {
      new import_obsidian.Notice("Invalid name.");
      return;
    }
    const parent = this.item.parent;
    const prefix = parent && !parent.isRoot() ? parent.path + "/" : "";
    const destination = (0, import_obsidian.normalizePath)(prefix + name);
    try {
      await this.plugin.renameItem(this.item, destination);
      this.close();
    } catch (e) {
      new import_obsidian.Notice("Rename failed: " + errorMessage(e));
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagsModal = class extends import_obsidian.Modal {
  constructor(app, file) {
    super(app);
    this.file = file;
  }
  onOpen() {
    var _a, _b;
    this.titleEl.setText("Tags");
    const current = frontmatterTags(
      (_b = (_a = this.app.metadataCache.getFileCache(this.file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.tags
    );
    const input = this.contentEl.createEl("textarea", {
      cls: "mc-tags-input",
      text: current.join("\n")
    });
    input.setAttr("placeholder", "project/client-a\nstatus/active");
    new import_obsidian.Setting(this.contentEl).setDesc("One tag per line. Tags are saved to standard Obsidian frontmatter.").addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(() => void this.submit(input.value))
    );
    input.focus();
  }
  async submit(value) {
    const tags = parseTagInput(value);
    try {
      await this.app.fileManager.processFrontMatter(this.file, (frontmatter) => {
        if (tags.length > 0) {
          frontmatter.tags = tags;
        } else {
          delete frontmatter.tags;
        }
      });
      this.close();
    } catch (e) {
      new import_obsidian.Notice("Could not update tags: " + errorMessage(e));
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AppearanceModal = class extends import_obsidian.Modal {
  constructor(app, plugin, item, onChange) {
    var _a, _b;
    super(app);
    this.plugin = plugin;
    this.item = item;
    this.onChange = onChange;
    this.icon = "";
    this.color = "";
    const appearance = plugin.appearanceFor(item.path);
    this.icon = (_a = appearance.icon) != null ? _a : DEFAULT_PAGE_ICON;
    this.color = (_b = appearance.color) != null ? _b : "";
  }
  onOpen() {
    this.titleEl.setText("Icon and color");
    this.contentEl.addClass("mc-appearance-modal");
    const preview = this.contentEl.createDiv({ cls: "mc-appearance-preview" });
    this.previewEl = preview.createSpan({ cls: "mc-appearance-preview-icon" });
    preview.createSpan({ text: this.item.name });
    this.renderPreview();
    new import_obsidian.Setting(this.contentEl).setName("Icon").setDesc("Use a Lucide icon name, such as notebook, book-open, star, or bookmark.").addText(
      (text) => text.setValue(this.icon).onChange((value) => {
        this.icon = value.trim();
        this.renderPreview();
      })
    );
    const iconGrid = this.contentEl.createDiv({ cls: "mc-picker-grid" });
    for (const icon of ICON_PRESETS) {
      const btn = iconGrid.createEl("button", { cls: "mc-icon-choice", attr: { type: "button" } });
      const iconEl = btn.createSpan();
      (0, import_obsidian.setIcon)(iconEl, icon);
      btn.setAttr("aria-label", icon);
      btn.addEventListener("click", () => {
        this.icon = icon;
        this.display();
      });
    }
    new import_obsidian.Setting(this.contentEl).setName("Color").setDesc("Choose a preset or enter any CSS color.").addText(
      (text) => text.setPlaceholder("default, #61afef, var(--text-accent)").setValue(this.color).onChange((value) => {
        this.color = value.trim();
        this.renderPreview();
      })
    );
    const colorGrid = this.contentEl.createDiv({ cls: "mc-picker-grid" });
    for (const color of COLOR_PRESETS) {
      const btn = colorGrid.createEl("button", { cls: "mc-color-choice", attr: { type: "button" } });
      btn.setAttr("aria-label", color || "Default color");
      if (color) btn.style.backgroundColor = color;
      btn.addEventListener("click", () => {
        this.color = color;
        this.display();
      });
    }
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Reset").onClick(async () => {
        delete this.plugin.settings.appearances[this.item.path];
        await this.plugin.saveSettings();
        this.onChange();
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(async () => {
        this.plugin.setAppearance(this.item.path, {
          icon: this.icon || DEFAULT_PAGE_ICON,
          color: this.color || void 0
        });
        await this.plugin.saveSettings();
        this.onChange();
        this.close();
      })
    );
  }
  display() {
    this.contentEl.empty();
    this.onOpen();
  }
  renderPreview() {
    if (!this.previewEl) return;
    this.previewEl.empty();
    (0, import_obsidian.setIcon)(this.previewEl, this.icon || DEFAULT_PAGE_ICON);
    this.previewEl.style.color = this.color;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MillerColumnsPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.renameOperations = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    (0, import_obsidian.addIcon)(ICON_ID, ICON_SVG);
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        void this.handleVaultRename(file, oldPath).catch((e) => {
          new import_obsidian.Notice("Could not finish page rename: " + errorMessage(e));
        });
      })
    );
    this.registerView(VIEW_TYPE_MILLER, (leaf) => new MillerColumnsView(leaf, this));
    this.addSettingTab(new MillerColumnsSettingTab(this.app, this));
    this.addRibbonIcon(ICON_ID, "Open Miller Columns", () => void this.activateView());
    this.addCommand({
      id: "open",
      name: "Open",
      callback: () => void this.activateView()
    });
  }
  async loadSettings() {
    const loaded = await this.loadData();
    const shortcuts = Array.isArray(loaded == null ? void 0 : loaded.shortcuts) ? loaded.shortcuts.filter(
      (shortcut) => Boolean(shortcut) && (shortcut.type === "path" || shortcut.type === "tag") && typeof shortcut.value === "string" && shortcut.value.length > 0
    ) : [];
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...loaded,
      columnWidths: Array.isArray(loaded == null ? void 0 : loaded.columnWidths) ? loaded.columnWidths : [],
      appearances: (loaded == null ? void 0 : loaded.appearances) && typeof loaded.appearances === "object" ? loaded.appearances : {},
      pinnedPaths: Array.isArray(loaded == null ? void 0 : loaded.pinnedPaths) ? Array.from(new Set(loaded.pinnedPaths.filter((path) => typeof path === "string"))) : [],
      shortcuts
    };
    this.settings.columnWidth = this.clampColumnWidth(this.settings.columnWidth);
    this.settings.columnWidths = this.settings.columnWidths.map(
      (width) => typeof width === "number" ? this.clampColumnWidth(width) : null
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MILLER)) {
      const view = leaf.view;
      if (view instanceof MillerColumnsView) {
        view.applySettings();
        view.refreshNavigation();
      }
    }
  }
  columnWidthFor(index) {
    const width = this.settings.columnWidths[index];
    return typeof width === "number" ? width : this.settings.columnWidth;
  }
  setColumnWidth(index, width) {
    const next = this.clampColumnWidth(width);
    this.settings.columnWidths[index] = next;
    return next;
  }
  resetColumnWidth(index) {
    this.settings.columnWidths[index] = null;
  }
  appearanceFor(path) {
    var _a;
    return (_a = this.settings.appearances[path]) != null ? _a : {};
  }
  setAppearance(path, appearance) {
    this.settings.appearances[path] = appearance;
  }
  isPinned(path) {
    return this.settings.pinnedPaths.includes(path);
  }
  async togglePinned(path) {
    if (this.isPinned(path)) {
      this.settings.pinnedPaths = this.settings.pinnedPaths.filter((candidate) => candidate !== path);
    } else {
      this.settings.pinnedPaths.push(path);
    }
    await this.saveSettings();
  }
  hasShortcut(type, value) {
    return this.settings.shortcuts.some(
      (shortcut) => shortcut.type === type && shortcut.value === value
    );
  }
  async toggleShortcut(type, value) {
    if (this.hasShortcut(type, value)) {
      this.settings.shortcuts = this.settings.shortcuts.filter(
        (shortcut) => shortcut.type !== type || shortcut.value !== value
      );
    } else {
      this.settings.shortcuts.push({ type, value });
    }
    await this.saveSettings();
  }
  async moveAppearance(oldPath, newPath) {
    let changed = false;
    const movePath = (path) => {
      if (path === oldPath) return newPath;
      if (path.startsWith(oldPath + "/")) return newPath + path.substring(oldPath.length);
      return path;
    };
    const next = {};
    for (const [path, appearance] of Object.entries(this.settings.appearances)) {
      const targetPath = movePath(path);
      if (targetPath !== path) changed = true;
      next[targetPath] = appearance;
    }
    const pinnedPaths = this.settings.pinnedPaths.map((path) => {
      const targetPath = movePath(path);
      if (targetPath !== path) changed = true;
      return targetPath;
    });
    const shortcuts = this.settings.shortcuts.map((shortcut) => {
      if (shortcut.type !== "path") return shortcut;
      const targetPath = movePath(shortcut.value);
      if (targetPath !== shortcut.value) changed = true;
      return { ...shortcut, value: targetPath };
    });
    if (!changed) return;
    this.settings.appearances = next;
    this.settings.pinnedPaths = Array.from(new Set(pinnedPaths));
    this.settings.shortcuts = shortcuts.filter(
      (shortcut, index, all) => all.findIndex(
        (candidate) => candidate.type === shortcut.type && candidate.value === shortcut.value
      ) === index
    );
    await this.saveSettings();
  }
  renameItem(item, destination) {
    if (!(item instanceof import_obsidian.TFolder)) {
      return this.app.fileManager.renameFile(item, destination);
    }
    const oldPath = item.path;
    const key = `${oldPath}
${destination}`;
    const existing = this.renameOperations.get(key);
    if (existing) return existing;
    let resolveOperation;
    let rejectOperation;
    const operation = new Promise((resolve, reject) => {
      resolveOperation = resolve;
      rejectOperation = reject;
    });
    this.renameOperations.set(key, operation);
    void this.performFolderRename(item, oldPath, destination).then(
      resolveOperation,
      rejectOperation
    );
    this.removeRenameOperationWhenSettled(key, operation);
    return operation;
  }
  async performFolderRename(folder, oldPath, destination) {
    const oldFolderName = folder.name;
    const newFolderName = destination.substring(destination.lastIndexOf("/") + 1);
    const oldPageName = `${oldFolderName}.md`;
    const newPageName = `${newFolderName}.md`;
    const companion = folder.children.find(
      (child) => child instanceof import_obsidian.TFile && child.name === oldPageName
    );
    if (companion && oldPageName !== newPageName) {
      const conflict = folder.children.find(
        (child) => child !== companion && child.name === newPageName
      );
      if (conflict) {
        throw new Error(`Could not rename attached page because ${newPageName} already exists.`);
      }
    }
    await this.app.fileManager.renameFile(folder, destination);
    if (companion && oldPageName !== newPageName) {
      await this.app.fileManager.renameFile(
        companion,
        (0, import_obsidian.normalizePath)(`${destination}/${newPageName}`)
      );
    }
    await this.moveAppearance(oldPath, destination);
  }
  handleVaultRename(file, oldPath) {
    const key = `${oldPath}
${file.path}`;
    const existing = this.renameOperations.get(key);
    if (existing) return existing;
    const operation = this.finishVaultRename(file, oldPath);
    this.renameOperations.set(key, operation);
    this.removeRenameOperationWhenSettled(key, operation);
    return operation;
  }
  removeRenameOperationWhenSettled(key, operation) {
    operation.then(
      () => this.renameOperations.delete(key),
      () => this.renameOperations.delete(key)
    );
  }
  async finishVaultRename(file, oldPath) {
    if (file instanceof import_obsidian.TFolder) {
      await new Promise((resolve) => window.setTimeout(resolve, 0));
      const oldFolderName = oldPath.substring(oldPath.lastIndexOf("/") + 1);
      const oldPageName = `${oldFolderName}.md`;
      const newPageName = `${file.name}.md`;
      if (oldPageName !== newPageName) {
        const oldPage = file.children.find(
          (child) => child instanceof import_obsidian.TFile && child.name === oldPageName
        );
        if (oldPage) {
          const conflict = file.children.find(
            (child) => child !== oldPage && child.name === newPageName
          );
          if (conflict) {
            new import_obsidian.Notice(`Could not rename ${oldPage.name} because ${newPageName} already exists.`);
          } else {
            await this.app.fileManager.renameFile(
              oldPage,
              (0, import_obsidian.normalizePath)(`${file.path}/${newPageName}`)
            );
          }
        }
      }
    }
    await this.moveAppearance(oldPath, file.path);
  }
  clampColumnWidth(width) {
    if (!Number.isFinite(width)) return DEFAULT_SETTINGS.columnWidth;
    return Math.min(MAX_COLUMN_WIDTH, Math.max(MIN_COLUMN_WIDTH, Math.round(width)));
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = (_a = workspace.getLeavesOfType(VIEW_TYPE_MILLER)[0]) != null ? _a : null;
    if (!leaf) {
      leaf = workspace.getLeftLeaf(false);
      if (!leaf) {
        new import_obsidian.Notice("Could not open Miller Columns in the left sidebar.");
        return;
      }
      await leaf.setViewState({ type: VIEW_TYPE_MILLER, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
};
var MillerColumnsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Default column width").setDesc("Width in pixels for columns that have not been resized.").addSlider(
      (slider) => slider.setLimits(MIN_COLUMN_WIDTH, MAX_COLUMN_WIDTH, 10).setValue(this.plugin.settings.columnWidth).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.columnWidth = value;
        await this.plugin.saveSettings();
      })
    ).addExtraButton(
      (button) => button.setIcon("reset").setTooltip("Reset to default").onClick(async () => {
        this.plugin.settings.columnWidth = DEFAULT_SETTINGS.columnWidth;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Individual column widths").setDesc("Drag the right edge of any column to resize that column depth. Double-click the edge to reset it.").addButton(
      (button) => button.setButtonText("Reset all").onClick(async () => {
        this.plugin.settings.columnWidths = [];
        await this.plugin.saveSettings();
      })
    );
  }
};
